### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by marcogorak** [projekt-matara/koa-demo#1]
MarcoGorak:koa-demo-master admin$ npm start

> koa-demo@0.0.1 start /Users/admin/Downloads/koa-demo-master
> nodemon app.js

[nodemon] 1.11.0
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `node app.js`
/Users/admin/Downloads/koa-demo-master/app.js:34
app.use(async (ctx, next) => {
              ^
SyntaxError: Unexpected token (
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:389:7)
    at startup (bootstrap_node.js:149:9)
[nodemon] app crashed - waiting for file changes before starting...

**Comment by marcogorak** [comment]
Sorry, my nodejs version is 6.x.x, i solved my problem.

**Comment by projekt-matara** [comment]
Haha it's all good! I've done the same countless times.
